export const GET_CLINIC_LIST_DATA = 'GET_CLINIC_LIST_DATA';
export const GET_SPECIALITY_LIST_DATA = 'GET_SPECIALITY_LIST_DATA';
export const GET_DOCTOR_LIST_DATA = 'GET_DOCTOR_LIST_DATA';

export const SHOW_CLINIC_SELECT = 'SHOW_CLINIC_SELECT';
export const SHOW_SPECIALITY_SELECT = 'SHOW_SPECIALITY_SELECT';
export const SHOW_DOCTOR_SELECT = 'GET_DOCTOR_SELECT';

export const SELECTED_CLINIC = 'SELECTED_CLINIC';
export const SELECTED_SPECIALITY = 'SELECTED_SPECIALITY';
export const SELECTED_DOCTOR = 'SELECTED_DOCTOR';

export const SET_FOLLOW_SETTINGS = 'SET_FOLLOW_SETTINGS';