const AppStates = {
  SELECT_CLINIC_PAGE: 'SELECT_CLINIC_PAGE',
  // LOAD_SPEC_LIST: 'LOAD_SPEC_LIST',
  SELECT_SPEC_PAGE: 'SELECT_SPEC_PAGE',
  SELECT_DOCTOR_PAGE: 'SELECT_DOCTOR_PAGE'
};

export default AppStates;